################################################################################## 
# Script to close alerts coming from a rule in SCOM 2007 R2 
# Initial version by Bob Cornelissen February 2012 
# 
# Update by Bob Cornelissen 15-March-2012. 
# 
################################################################################## 
# Load snapin and connect to RMS 
# Remember to enter the fqdn name of the RMS below! 
$RMS = "enter.fqdn.name.here" 
Add-PSSnapin "Microsoft.EnterpriseManagement.OperationsManager.Client" 
Set-Location "OperationsManagerMonitoring::" 
New-ManagementGroupConnection -ConnectionString:$RMS 
Set-Location $RMS 
 
# Adjust the amount of hours to your liking, by default it is set at 96 hours. 
$AgeHours = 96 
 
# Find alerts with New state which were created by a rule. 
# This will close alerts older than the specified amount of hours if coming from a rule. 
get-alert -criteria 'ResolutionState=''0'' AND IsMonitorAlert=''False''' |where {$_.LastModified -le (Get-Date).addhours(-$AgeHours)} | resolve-alert -comment "Close old alerts generated by rules" | out-null 
 
#end of script 
